Add tests for curl, URL basic-auth, and wget
rusty-ferris-club/shellclear pull request #66
Opened 2022-11-26 13:40 UTC by MegaManSec

cURL: The -u flag and the 'Authorization' header may contain plaintext or base64-encoded secrets.
URL: A URL may contain a login combination.
wget: various flags pass around username and passsword combinations.

2022-11-26 22:13 UTC, MegaManSec commented
Actually it seems these do not work (only now able to test). Is the format wrong?
I was using regex101.com to make these, using the 'golang' flavor, which afaik is sufficiently similar to Rust.

2022-11-27 06:44 UTC, kaplanelad commented
Thanks @MegaManSec for your contributing,
I have test for each rule in this folder you can ream more [here](https://github.com/rusty-ferris-club/shellclear/blob/main/CONTRIBUTING.md#new-pattern)

Can you please add the following tests?

2022-11-27 08:42 UTC, MegaManSec commented
Should be ok now.

2022-12-04 07:28 UTC, kaplanelad requested changes
Thanks looks good!

You need to add the *.snap files to the commit as well. i missed it in the contributing guid (added it just now) https://github.com/rusty-ferris-club/shellclear/blob/main/CONTRIBUTING.md#create-test-snapshots

2022-12-04 07:28 UTC, kaplanelad commented on shellclear/tests/suites_sensitive_patterns/curl_basic_auth.yaml
> +  expected: YmFzZTY0OnBhc3N3b3JkCg==
the expected value is not `$SECRET_VAR`?

2022-12-12 08:59 UTC, kaplanelad approved these changes
Thank you for contributing to my project! Your contribution is an important part of the project's success, and I am grateful for your support.

2022-12-12 08:59 UTC, merged